export class EmojiPicker {
  private editor: any
  private emojiPickerElement: HTMLElement | null = null
  private recentEmojis: string[] = []
  private maxRecentEmojis = 16

  private loadRecentEmojis(): void {
    const saved = localStorage.getItem('recentEmojis')
    this.recentEmojis = saved ? JSON.parse(saved) : []
  }

  constructor(editor: any) {
    this.editor = editor
    this.loadRecentEmojis()
    this.handleClickOutside = this.handleClickOutside.bind(this)
  }

  private handleClickOutside = (event: MouseEvent): void => {
    if (this.emojiPickerElement && !this.emojiPickerElement.contains(event.target as Node)) {
      this.emojiPickerElement.style.display = "none"
      document.removeEventListener("click", this.handleClickOutside)
    }
  }

  public show(): void {
    // Create emoji picker if it doesn't exist
    if (!this.emojiPickerElement) {
      this.createEmojiPicker()
    }

    // Position the emoji picker
    const toolbar = this.editor.getToolbar()
    const button = toolbar.querySelector('[data-command="insertEmoji"]')
    if (button && this.emojiPickerElement) {
      const buttonRect = button.getBoundingClientRect()
      const containerRect = this.editor.getContainer().getBoundingClientRect()

      this.emojiPickerElement.style.top = `${buttonRect.bottom - containerRect.top}px`
      this.emojiPickerElement.style.left = `${buttonRect.left - containerRect.left}px`
      this.emojiPickerElement.style.display = "block"
    }

    // Add click outside listener
    document.addEventListener("click", this.handleClickOutside)
  }

  private createEmojiPicker(): void {
    this.emojiPickerElement = document.createElement("div")
    this.emojiPickerElement.className = "emoji-picker"
    this.emojiPickerElement.style.display = "none"

    // Create tabs
    const tabs = document.createElement("div")
    tabs.className = "emoji-tabs"

    const categories = [
      { id: "recent", name: "Recent", icon: "🕒" },
      { id: "smileys", name: "Smileys & Emotion", icon: "😀" },
      { id: "people", name: "People & Body", icon: "👋" },
      { id: "animals", name: "Animals & Nature", icon: "🐶" },
      { id: "food", name: "Food & Drink", icon: "🍔" },
      { id: "travel", name: "Travel & Places", icon: "✈️" },
      { id: "activities", name: "Activities", icon: "⚽" },
      { id: "objects", name: "Objects", icon: "💡" },
      { id: "symbols", name: "Symbols", icon: "❤️" },
      { id: "flags", name: "Flags", icon: "🏁" },
    ]

    categories.forEach((category) => {
      const tab = document.createElement("div")
      tab.className = "emoji-tab"
      tab.setAttribute("data-category", category.id)
      tab.innerHTML = category.icon
      tab.title = category.name
      tab.addEventListener("click", () => this.switchCategory(category.id))
      tabs.appendChild(tab)
    })

    // Create emoji container
    const emojiContainer = document.createElement("div")
    emojiContainer.className = "emoji-container"

    // Create search input
    const searchContainer = document.createElement("div")
    searchContainer.className = "emoji-search-container"

    const searchInput = document.createElement("input")
    searchInput.type = "text"
    searchInput.className = "emoji-search"
    searchInput.placeholder = "Search emojis..."
    searchInput.addEventListener("input", () => this.searchEmojis(searchInput.value))

    searchContainer.appendChild(searchInput)

    // Assemble emoji picker
    this.emojiPickerElement.appendChild(searchContainer)
    this.emojiPickerElement.appendChild(tabs)
    this.emojiPickerElement.appendChild(emojiContainer)

    // Add to editor container
    this.editor.getContainer().appendChild(this.emojiPickerElement)

    // Load initial category (recent)
    this.switchCategory("recent")
  }

  private switchCategory(categoryId: string): void {
    if (!this.emojiPickerElement) return

    // Update active tab
    const tabs = this.emojiPickerElement.querySelectorAll(".emoji-tab")
    tabs.forEach((tab) => {
      if (tab.getAttribute("data-category") === categoryId) {
        tab.classList.add("active")
      } else {
        tab.classList.remove("active")
      }
    })

    // Get emoji container
    const emojiContainer = this.emojiPickerElement.querySelector(".emoji-container")
    if (!emojiContainer) return

    // Clear container
    emojiContainer.innerHTML = ""

    // Load emojis for the category
    let emojis: string[] = []

    if (categoryId === "recent") {
      emojis = this.recentEmojis
    } else {
      emojis = this.getEmojisForCategory(categoryId)
    }

    // Add emojis to container
    emojis.forEach((emoji) => {
      const emojiElement = document.createElement("span")
      emojiElement.className = "emoji"
      emojiElement.textContent = emoji
      emojiElement.addEventListener("click", () => this.insertEmoji(emoji))
      emojiContainer.appendChild(emojiElement)
    })
  }

  private insertEmoji(emoji: string): void {
    // Insert emoji at current cursor position
    this.editor.insertText(emoji);
    
    // Add to recent emojis
    if (!this.recentEmojis.includes(emoji)) {
      this.recentEmojis.unshift(emoji);
      if (this.recentEmojis.length > this.maxRecentEmojis) {
        this.recentEmojis.pop();
      }
      localStorage.setItem('recentEmojis', JSON.stringify(this.recentEmojis));
    }

    // Hide picker after selection
    if (this.emojiPickerElement) {
      this.emojiPickerElement.style.display = "none";
    }
  }

  private searchEmojis(query: string): void {
    if (!this.emojiPickerElement) return;

    const emojiContainer = this.emojiPickerElement.querySelector(".emoji-container");
    if (!emojiContainer) return;

    // Clear container
    emojiContainer.innerHTML = "";

    // Search through all categories
    const allEmojis: string[] = Object.values(this.getEmojisForCategory("smileys"))
      .concat(...Object.keys(this.getEmojisForCategory)
        .filter(category => category !== "smileys")
        .map(category => this.getEmojisForCategory(category)));

    // Filter emojis based on search query
    const filteredEmojis = allEmojis.filter(emoji => 
      emoji.toLowerCase().includes(query.toLowerCase())
    );

    // Display filtered emojis
    filteredEmojis.forEach((emoji) => {
      const emojiElement = document.createElement("span");
      emojiElement.className = "emoji";
      emojiElement.textContent = emoji;
      emojiElement.addEventListener("click", () => this.insertEmoji(emoji));
      emojiContainer.appendChild(emojiElement);
    });
  }

  private getEmojisForCategory(categoryId: string): string[] {
    // This is a simplified implementation
    // In a real implementation, you would have a complete emoji database
    const emojiMap: Record<string, string[]> = {
      smileys: [
        "😀",
        "😃",
        "😄",
        "😁",
        "😆",
        "😅",
        "😂",
        "🤣",
        "😊",
        "😇",
        "🙂",
        "🙃",
        "😉",
        "😌",
        "😍",
        "🥰",
        "😘",
        "😗",
        "😙",
        "😚",
        "😋",
        "😛",
        "😝",
        "😜",
        "🤪",
        "🤨",
        "🧐",
        "🤓",
        "😎",
        "🤩",
        "🥳",
        "😏",
        "😒",
        "😞",
        "😔",
        "😟",
        "😕",
        "🙁",
        "☹️",
        "😣",
        "😖",
        "😫",
        "😩",
        "🥺",
        "😢",
        "😭",
        "😤",
        "😠",
        "😡",
        "🤬",
        "🤯",
        "😳",
        "🥵",
        "🥶",
        "😱",
        "😨",
        "😰",
        "😥",
        "😓",
        "🤗",
        "🤔",
        "🤭",
        "🤫",
        "🤥",
        "😶",
        "😐",
        "😑",
        "😬",
        "🙄",
        "😯",
        "😦",
        "😧",
        "😮",
        "😲",
        "🥱",
        "😴",
        "🤤",
        "😪",
        "😵",
        "🤐",
        "🥴",
        "🤢",
        "🤮",
        "🤧",
        "😷",
        "🤒",
        "🤕",
      ],
      people: [
        "👋",
        "🤚",
        "🖐️",
        "✋",
        "🖖",
        "👌",
        "🤏",
        "✌️",
        "🤞",
        "🤟",
        "🤘",
        "🤙",
        "👈",
        "👉",
        "👆",
        "🖕",
        "👇",
        "☝️",
        "👍",
        "👎",
        "✊",
        "👊",
        "🤛",
        "🤜",
        "👏",
        "🙌",
        "👐",
        "🤲",
        "🤝",
        "🙏",
        "✍️",
        "💅",
        "🤳",
        "💪",
        "🦾",
        "🦿",
        "🦵",
        "🦶",
        "👂",
        "🦻",
        "👃",
        "🧠",
        "🦷",
        "🦴",
        "👀",
        "👁️",
        "👅",
        "👄",
        "💋",
        "🩸",
      ],
      animals: [
        "🐶",
        "🐱",
        "🐭",
        "🐹",
        "🐰",
        "🦊",
        "🐻",
        "🐼",
        "🐨",
        "🐯",
        "🦁",
        "🐮",
        "🐷",
        "🐽",
        "🐸",
        "🐵",
        "🙈",
        "🙉",
        "🙊",
        "🐒",
        "🐔",
        "🐧",
        "🐦",
        "🐤",
        "🐣",
        "🐥",
        "🦆",
        "🦅",
        "🦉",
        "🦇",
        "🐺",
        "🐗",
        "🐴",
        "🦄",
        "🐝",
        "🐛",
        "🦋",
        "🐌",
        "🐞",
        "🐜",
        "🦟",
        "🦗",
        "🕷️",
        "🕸️",
        "🦂",
        "🐢",
        "🐍",
        "🦎",
        "🦖",
        "🦕",
        "🐙",
        "🦑",
        "🦐",
        "🦞",
        "🦀",
        "🐡",
        "🐠",
        "🐟",
        "🐬",
        "🐳",
        "🐋",
        "🦈",
        "🐊",
        "🐅",
        "🐆",
        "🦓",
        "🦍",
        "🦧",
        "🐘",
        "🦛",
        "🦏",
        "🐪",
        "🐫",
        "🦒",
        "🦘",
        "🐃",
        "🐂",
        "🐄",
        "🐎",
        "🐖",
        "🐏",
        "🐑",
        "🦙",
        "🐐",
        "🦌",
        "🐕",
        "🐩",
        "🦮",
        "🐕‍🦺",
        "🐈",
        "🐓",
        "🦃",
        "🦚",
        "🦜",
        "🦢",
        "🦩",
        "🕊️",
        "🐇",
        "🦝",
        "🦨",
        "🦡",
        "🦦",
        "🦥",
        "🐁",
        "🐀",
        "🐿️",
        "🦔",
        "🐾",
        "🐉",
        "🐲",
        "🌵",
        "🎄",
        "🌲",
        "🌳",
        "🌴",
        "🌱",
        "🌿",
        "☘️",
        "🍀",
        "🎍",
        "🎋",
        "🍃",
        "🍂",
        "🍁",
        "🍄",
        "🌾",
        "💐",
        "🌷",
        "🌹",
        "🥀",
        "🌺",
        "🌸",
        "🌼",
        "🌻",
        "🌞",
        "🌝",
        "🌛",
        "🌜",
        "🌚",
        "🌕",
        "🌖",
        "🌗",
        "🌘",
        "🌑",
        "🌒",
        "🌓",
        "🌔",
        "🌙",
        "🌎",
        "🌍",
        "🌏",
        "🪐",
        "💫",
        "⭐",
        "🌟",
        "✨",
        "⚡",
        "☄️",
        "💥",
        "🔥",
        "🌪️",
        "🌈",
        "☀️",
        "🌤️",
        "⛅",
        "🌥️",
        "☁️",
        "🌦️",
        "🌧️",
        "⛈️",
        "🌩️",
        "🌨️",
        "❄️",
        "☃️",
        "⛄",
        "🌬️",
        "💨",
        "💧",
        "💦",
        "☔",
        "☂️",
        "🌊",
        "🌫️",
      ],
      food: [
        "🍏",
        "🍎",
        "🍐",
        "🍊",
        "🍋",
        "🍌",
        "🍉",
        "🍇",
        "🍓",
        "🍈",
        "🍒",
        "🍑",
        "🥭",
        "🍍",
        "🥥",
        "🥝",
        "🍅",
        "🍆",
        "🥑",
        "🥦",
        "🥬",
        "🥒",
        "🌶️",
        "🌽",
        "🥕",
        "🧄",
        "🧅",
        "🥔",
        "🍠",
        "🥐",
        "🥯",
        "🍞",
        "🥖",
        "🥨",
        "🧀",
        "🥚",
        "🍳",
        "🧈",
        "🥞",
        "🧇",
        "🥓",
        "🥩",
        "🍗",
        "🍖",
        "🦴",
        "🌭",
        "🍔",
        "🍟",
        "🍕",
        "🥪",
        "🥙",
        "🧆",
        "🌮",
        "🌯",
        "🥗",
        "🥘",
        "🥫",
        "🍝",
        "🍜",
        "🍲",
        "🍛",
        "🍣",
        "🍱",
        "🥟",
        "🦪",
        "🍤",
        "🍙",
        "🍚",
        "🍘",
        "🍥",
        "🥠",
        "🥮",
        "🍢",
        "🍡",
        "🍧",
        "🍨",
        "🍦",
        "🥧",
        "🧁",
        "🍰",
        "🎂",
        "🍮",
        "🍭",
        "🍬",
        "🍫",
        "🍿",
        "🍩",
        "🍪",
        "🌰",
        "🥜",
        "🍯",
        "🥛",
        "🍼",
        "☕",
        "🍵",
        "🧃",
        "🥤",
        "🍶",
        "🍺",
        "🍻",
        "🥂",
        "🍷",
        "🥃",
        "🍸",
        "🍹",
        "🧉",
        "🍾",
        "🧊",
        "🥄",
        "🍴",
        "🍽️",
        "🥣",
        "🥡",
        "🥢",
        "🧂",
      ],
      travel: [
        "✈️",
        "🛫",
        "🛬",
        "🛩️",
        "💺",
        "🚁",
        "🚀",
        "🛸",
        "🚂",
        "🚃",
        "🚄",
        "🚅",
        "🚆",
        "🚇",
        "🚈",
        "🚉",
        "🚊",
        "🚝",
        "🚞",
        "🚋",
        "🚌",
        "🚍",
        "🚎",
        "🚐",
        "🚑",
        "🚒",
        "🚓",
        "🚔",
        "🚕",
        "🚖",
        "🚗",
        "🚘",
        "🚙",
        "🚚",
        "🚛",
        "🚜",
        "🏎️",
        "🏍️",
        "🛵",
        "🦽",
        "🦼",
        "🛺",
        "🚲",
        "🛴",
        "🛹",
        "🚏",
        "🛣️",
        "🛤️",
        "🛢️",
        "⛽",
        "🚨",
        "🚥",
        "🚦",
        "🛑",
        "🚧",
        "⚓",
        "⛵",
        "🛶",
        "🚤",
        "🛳️",
        "⛴️",
        "🚢",
        "🚟",
        "🚠",
        "🚡",
        "🚁",
        "🛰️",
        "🚀",
        "🛸",
        "🛎️",
        "🧳",
        "⌛",
        "⏳",
        "⌚",
        "⏰",
        "⏱️",
        "⏲️",
        "🕰️",
        "🕛",
        "🕧",
        "🕐",
        "🕜",
        "🕑",
        "🕝",
        "🕒",
        "🕞",
        "🕓",
        "🕟",
        "🕔",
        "🕠",
        "🕕",
        "🕡",
        "🕖",
        "🕢",
        "🕗",
        "🕣",
        "🕘",
        "🕤",
        "🕙",
        "🕥",
        "🕚",
        "🕦",
        "🌑",
        "🌒",
        "🌓",
        "🌔",
        "🌕",
        "🌖",
        "🌗",
        "🌘",
        "🌙",
        "🌚",
        "🌛",
        "🌜",
        "🌡️",
        "☀️",
        "🌝",
        "🌞",
        "🪐",
        "⭐",
        "🌟",
        "🌠",
        "🌌",
        "☁️",
        "⛅",
        "⛈️",
        "🌤️",
        "🌥️",
        "🌦️",
        "🌧️",
        "🌨️",
        "🌩️",
        "🌪️",
        "🌫️",
        "🌬️",
        "🌀",
        "🌈",
        "🌂",
        "☂️",
        "☔",
        "⛱️",
        "⚡",
        "❄️",
        "☃️",
        "⛄",
        "☄️",
        "🔥",
        "💧",
        "🌊",
      ],
      activities: [
        "⚽",
        "🏀",
        "🏈",
        "⚾",
        "🥎",
        "🎾",
        "🏐",
        "🏉",
        "🥏",
        "🎱",
        "🪀",
        "🏓",
        "🏸",
        "🏒",
        "🏑",
        "🥍",
        "🏏",
        "🥅",
        "⛳",
        "🪁",
        "🏹",
        "🎣",
        "🤿",
        "🥊",
        "🥋",
        "🎽",
        "🛹",
        "🛷",
        "⛸️",
        "🥌",
        "🎿",
        "⛷️",
        "🏂",
        "🪂",
        "🏋️",
        "🏋️‍♀️",
        "🏋️‍♂️",
        "🤼",
        "🤼‍♀️",
        "🤼‍♂️",
        "🤸",
        "🤸‍♀️",
        "🤸‍♂️",
        "⛹️",
        "⛹️‍♀️",
        "⛹️‍♂️",
        "🤺",
        "🤾",
        "🤾‍♀️",
        "🤾‍♂️",
        "🏌️",
        "🏌️‍♀️",
        "🏌️‍♂️",
        "🏇",
        "🧘",
        "🧘‍♀️",
        "🧘‍♂️",
        "🏄",
        "🏄‍♀️",
        "🏄‍♂️",
        "🏊",
        "🏊‍♀️",
        "🏊‍♂️",
        "🤽",
        "🤽‍♀️",
        "🤽‍♂️",
        "🚣",
        "🚣‍♀️",
        "🚣‍♂️",
        "🧗",
        "🧗‍♀️",
        "🧗‍♂️",
        "🚵",
        "🚵‍♀️",
        "🚵‍♂️",
        "🚴",
        "🚴‍♀️",
        "🚴‍♂️",
        "🏆",
        "🥇",
        "🥈",
        "🥉",
        "🏅",
        "🎖️",
        "🏵️",
        "🎗️",
        "🎫",
        "🎟️",
        "🎪",
        "🤹",
        "🤹‍♀️",
        "🤹‍♂️",
        "🎭",
        "🩰",
        "🎨",
        "🎬",
        "🎤",
        "🎧",
        "🎼",
        "🎹",
        "🥁",
        "🎷",
        "🎺",
        "🎸",
        "🪕",
        "🎻",
        "🎲",
        "♟️",
        "🎯",
        "🎳",
        "🎮",
        "🎰",
        "🧩",
      ],
      objects: [
        "💡",
        "🔦",
        "🏮",
        "🪔",
        "📔",
        "📕",
        "📖",
        "📗",
        "📘",
        "📙",
        "📚",
        "📓",
        "📒",
        "📃",
        "📜",
        "📄",
        "📰",
        "🗞️",
        "📑",
        "🔖",
        "🏷️",
        "💰",
        "💴",
        "💵",
        "💶",
        "💷",
        "💸",
        "💳",
        "🧾",
        "💹",
        "✉️",
        "📧",
        "📨",
        "📩",
        "📤",
        "📥",
        "📦",
        "📫",
        "📪",
        "📬",
        "📭",
        "📮",
        "🗳️",
        "✏️",
        "✒️",
        "🖋️",
        "🖊️",
        "🖌️",
        "🖍️",
        "📝",
        "💼",
        "📁",
        "📂",
        "🗂️",
        "📅",
        "📆",
        "🗒️",
        "🗓️",
        "📇",
        "📈",
        "📉",
        "📊",
        "📋",
        "📌",
        "📍",
        "📎",
        "🖇️",
        "📏",
        "📐",
        "✂️",
        "🗃️",
        "🗄️",
        "🗑️",
        "🔒",
        "🔓",
        "🔏",
        "🔐",
        "🔑",
        "🗝️",
        "🔨",
        "🪓",
        "⛏️",
        "⚒️",
        "🛠️",
        "🗡️",
        "⚔️",
        "🔫",
        "🏹",
        "🛡️",
        "🔧",
        "🔩",
        "⚙️",
        "🗜️",
        "⚖️",
        "🦯",
        "🔗",
        "⛓️",
        "🧰",
        "🧲",
        "⚗️",
        "🧪",
        "🧫",
        "🧬",
        "🔬",
        "🔭",
        "📡",
        "💉",
        "🩸",
        "💊",
        "🩹",
        "🩺",
        "🚪",
        "🛏️",
        "🛋️",
        "🪑",
        "🚽",
        "🚿",
        "🛁",
        "🪒",
        "🧴",
        "🧷",
        "🧹",
        "🧺",
        "🧻",
        "🧼",
        "🧽",
        "🧯",
        "🛒",
        "🚬",
        "⚰️",
        "⚱️",
        "🗿",
      ],
      symbols: [
        "❤️",
        "🧡",
        "💛",
        "💚",
        "💙",
        "💜",
        "🖤",
        "🤍",
        "🤎",
        "💔",
        "❣️",
        "💕",
        "💞",
        "💓",
        "💗",
        "💖",
        "💘",
        "💝",
        "💟",
        "☮️",
        "✝️",
        "☪️",
        "🕉️",
        "☸️",
        "✡️",
        "🔯",
        "🕎",
        "☯️",
        "☦️",
        "🛐",
        "⛎",
        "♈",
        "♉",
        "♊",
        "♋",
        "♌",
        "♍",
        "♎",
        "♏",
        "♐",
        "♑",
        "♒",
        "♓",
        "🆔",
        "⚛️",
        "🉑",
        "☢️",
        "☣️",
        "📴",
        "📳",
        "🈶",
        "🈚",
        "🈸",
        "🈺",
        "🈷️",
        "✴️",
        "🆚",
        "💮",
        "🉐",
        "㊙️",
        "㊗️",
        "🈴",
        "🈵",
        "🈹",
        "🈲",
        "🅰️",
        "🅱️",
        "🆎",
        "🆑",
        "🅾️",
        "🆘",
        "❌",
        "⭕",
        "🛑",
        "⛔",
        "📛",
        "🚫",
        "💯",
        "💢",
        "♨️",
        "🚷",
        "🚯",
        "🚳",
        "🚱",
        "🔞",
        "📵",
        "🚭",
        "❗",
        "❕",
        "❓",
        "❔",
        "‼️",
        "⁉️",
        "🔅",
        "🔆",
        "〽️",
        "⚠️",
        "🚸",
        "🔱",
        "⚜️",
        "🔰",
        "♻️",
        "✅",
        "🈯",
        "💹",
        "❇️",
        "✳️",
        "❎",
        "🌐",
        "💠",
        "Ⓜ️",
        "🌀",
        "💤",
        "🏧",
        "🚾",
        "♿",
        "🅿️",
        "🈳",
        "🈂️",
        "🛂",
        "🛃",
        "🛄",
        "🛅",
        "🚹",
        "🚺",
        "🚼",
        "⚧",
        "🚻",
        "🚮",
        "🎦",
        "📶",
        "🈁",
        "🔣",
        "ℹ️",
        "🔤",
        "🔡",
        "🔠",
        "🆖",
        "🆗",
        "🆙",
        "🆒",
        "🆕",
        "🆓",
        "0️⃣",
        "1️⃣",
        "2️⃣",
        "3️⃣",
        "4️⃣",
        "5️⃣",
        "6️⃣",
        "7️⃣",
        "8️⃣",
        "9️⃣",
        "🔟",
        "🔢",
        "#️⃣",
        "*️⃣",
        "⏏️",
        "▶️",
        "⏸️",
        "⏯️",
        "⏹️",
        "⏺️",
        "⏭️",
        "⏮️",
        "⏩",
        "⏪",
        "⏫",
        "⏬",
        "◀️",
        "🔼",
        "🔽",
        "➡️",
        "⬅️",
        "⬆️",
        "⬇️",
        "↗️",
        "↘️",
        "↙️",
        "↖️",
        "↕️",
        "↔️",
        "↪️",
        "↩️",
        "⤴️",
        "⤵️",
        "🔀",
        "🔁",
        "🔂",
        "🔄",
        "🔃",
        "🎵",
        "🎶",
        "➕",
        "➖",
        "➗",
        "✖️",
        "♾️",
        "💲",
        "💱",
        "™️",
        "©️",
        "®️",
        "〰️",
        "➰",
        "➿",
        "🔚",
        "🔙",
        "🔛",
        "🔝",
        "🔜",
        "✔️",
        "☑️",
        "🔘",
        "🔴",
        "🟠",
        "🟡",
        "🟢",
        "🔵",
        "🟣",
        "⚫",
        "⚪",
        "🟤",
        "🔺",
        "🔻",
        "🔸",
        "🔹",
        "🔶",
        "🔷",
        "🔳",
        "🔲",
        "▪️",
        "▫️",
        "◾",
        "◽",
        "◼️",
        "◻️",
        "🟥",
        "🟧",
        "🟨",
        "🟩",
        "🟦",
        "🟪",
        "⬛",
        "⬜",
        "🟫",
        "🔈",
        "🔇",
        "🔉",
        "🔊",
        "🔔",
        "🔕",
        "📣",
        "📢",
        "👁️‍🗨️",
        "💬",
        "💭",
        "🗯️",
        "♠️",
        "♣️",
        "♥️",
        "♦️",
        "🃏",
        "🎴",
        "🀄",
        "🕐",
        "🕑",
        "🕒",
        "🕓",
        "🕔",
        "🕕",
        "🕖",
        "🕗",
        "🕘",
        "🕙",
        "🕚",
        "🕛",
        "🕜",
        "🕝",
        "🕞",
        "🕟",
        "🕠",
        "🕡",
        "🕢",
        "🕣",
        "🕤",
        "🕥",
        "🕦",
        "🕧",
      ],
      flags: [
        "🏁",
        "🚩",
        "🎌",
        "🏴",
        "🏳️",
        "🏳️‍🌈",
        "🏳️‍⚧️",
        "🏴‍☠️",
        "🇦🇨",
        "🇦🇩",
        "🇦🇪",
        "🇦🇫",
        "🇦🇬",
        "🇦🇮",
        "🇦🇱",
        "🇦🇲",
        "🇦🇴",
        "🇦🇶",
        "🇦🇷",
        "🇦🇸",
        "🇦🇹",
        "🇦🇺",
        "🇦🇼",
        "🇦🇽",
        "🇦🇿",
        "🇧🇦",
        "🇧🇧",
        "🇧🇩",
        "🇧🇪",
        "🇧🇫",
        "🇧🇬",
        "🇧🇭",
        "🇧🇮",
        "🇧🇯",
        "🇧🇱",
        "🇧🇲",
        "🇧🇳",
        "🇧🇴",
        "🇧🇶",
        "🇧🇷",
        "🇧🇸",
        "🇧🇹",
        "🇧🇻",
        "🇧🇼",
        "🇧🇾",
        "🇧🇿",
        "🇨🇦",
        "🇨🇨",
        "🇨🇩",
        "🇨🇫",
        "🇨🇬",
        "🇨🇭",
        "🇨🇮",
        "🇨🇰",
        "🇨🇱",
        "🇨🇲",
        "🇨🇳",
        "🇨🇴",
        "🇨🇵",
        "🇨🇷",
        "🇨🇺",
        "🇨🇻",
        "🇨🇼",
        "🇨🇽",
        "🇨🇾",
        "🇨🇿",
        "🇩🇪",
        "🇩🇬",
        "🇩🇯",
        "🇩🇰",
        "🇩🇲",
        "🇩🇴",
        "🇩🇿",
        "🇪🇦",
        "🇪🇨",
        "🇪🇪",
        "🇪🇬",
        "🇪🇭",
        "🇪🇷",
        "🇪🇸",
        "🇪🇹",
        "🇪🇺",
        "🇫🇮",
        "🇫🇯",
        "🇫🇰",
        "🇫🇲",
        "🇫🇴",
        "🇫🇷",
        "🇬🇦",
        "🇬🇧",
        "🇬🇩",
        "🇬🇪",
        "🇬🇫",
        "🇬🇬",
        "🇬🇭",
        "🇬🇮",
        "🇬🇱",
        "🇬🇲",
        "🇬🇳",
        "🇬🇵",
        "🇬🇶",
        "🇬🇷",
        "🇬🇸",
        "🇬🇹",
        "🇬🇺",
        "🇬🇼",
        "🇬🇾",
        "🇭🇰",
        "🇭🇲",
        "🇭🇳",
        "🇭🇷",
        "🇭🇹",
        "🇭🇺"]
      }
    }
  }
